//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NodeSystemTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExpectedOutputs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExpectedOutputs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NodeSystemTests.ExpectedOutputs", typeof(ExpectedOutputs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new SingleChildNode(&quot;root&quot;,
        ///    new TwoChildrenNode(&quot;child1&quot;,
        ///        new ManyChildrenNode(&quot;child11&quot;,
        ///            new NoChildrenNode(&quot;leaf1&quot;),
        ///            null,
        ///            new SingleChildNode(&quot;child112&quot;,
        ///                null)),
        ///        new SingleChildNode(&quot;child2&quot;,
        ///            null))).
        /// </summary>
        internal static string test1 {
            get {
                return ResourceManager.GetString("test1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new SingleChildNode(&quot;root&quot;,
        ///    new TwoChildrenNode(&quot;child1&quot;,
        ///        new TwoChildrenNode(&quot;child11&quot;,
        ///            new NoChildrenNode(&quot;leaf1&quot;),
        ///            new NoChildrenNode(&quot;child112&quot;)),
        ///        new NoChildrenNode(&quot;child2&quot;))).
        /// </summary>
        internal static string test1_Transformed {
            get {
                return ResourceManager.GetString("test1_Transformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new SingleChildNode(&quot;root&quot;,
        ///    new TwoChildrenNode(&quot;child1&quot;,
        ///        new NoChildrenNode(&quot;leaf1&quot;),
        ///        new SingleChildNode(&quot;child2&quot;,
        ///            new NoChildrenNode(&quot;leaf2&quot;)))).
        /// </summary>
        internal static string test2 {
            get {
                return ResourceManager.GetString("test2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new SingleChildNode(&quot;root&quot;,
        ///    new TwoChildrenNode(&quot;child1&quot;,
        ///        new NoChildrenNode(&quot;leaf1&quot;),
        ///        new SingleChildNode(&quot;child2&quot;,
        ///            new NoChildrenNode(&quot;leaf2&quot;)))).
        /// </summary>
        internal static string test2_Transformed {
            get {
                return ResourceManager.GetString("test2_Transformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new ManyChildrenNode(&quot;root&quot;,
        ///    new ManyChildrenNode(&quot;child1&quot;,
        ///        new ManyChildrenNode(&quot;leaf1&quot;),
        ///        new ManyChildrenNode(&quot;child2&quot;,
        ///            new ManyChildrenNode(&quot;leaf2&quot;)))).
        /// </summary>
        internal static string test3 {
            get {
                return ResourceManager.GetString("test3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new SingleChildNode(&quot;root&quot;,
        ///    new TwoChildrenNode(&quot;child1&quot;,
        ///        new NoChildrenNode(&quot;leaf1&quot;),
        ///        new SingleChildNode(&quot;child2&quot;,
        ///            new NoChildrenNode(&quot;leaf2&quot;)))).
        /// </summary>
        internal static string test3_Transformed {
            get {
                return ResourceManager.GetString("test3_Transformed", resourceCulture);
            }
        }
    }
}
