//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NodeSystemTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestOracle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestOracle() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NodeSystemTests.TestOracle", typeof(TestOracle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // result is:
        ///// new SingleChildNode(&quot;root&quot;,
        /////     new TwoChildrenNode(&quot;child1&quot;,
        /////         new ManyChildrenNode(&quot;child11&quot;,
        /////             new NoChildrenNode(&quot;leaf1&quot;),
        /////             null,
        /////             new SingleChildNode(&quot;child112&quot;,
        /////                 null)),
        /////         new SingleChildNode(&quot;child2&quot;,
        /////             null))).
        /// </summary>
        internal static string IoCTests_TestData {
            get {
                return ResourceManager.GetString("IoCTests_TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // result is:
        ///// new SingleChildNode(&quot;root&quot;,
        /////     new TwoChildrenNode(&quot;child1&quot;,
        /////         new TwoChildrenNode(&quot;child11&quot;,
        /////             new NoChildrenNode(&quot;leaf1&quot;),
        /////             new NoChildrenNode(&quot;child112&quot;)),
        /////         new NoChildrenNode(&quot;child2&quot;))).
        /// </summary>
        internal static string IoCTests_TestData_NoTransformed {
            get {
                return ResourceManager.GetString("IoCTests_TestData_NoTransformed", resourceCulture);
            }
        }
    }
}
